name: Deploy Frontend to statsb

on:
  push:
    branches: [ master ]  # Change this to your main branch name if different
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    name: Deploy to statsb
    runs-on: [self-hosted, statsb]  # Specifies the self-hosted runner with label 'statsb'
    
    steps:
      - name: Pull latest code
        run: cd /home/statsb/statsb-app && git pull origin master

      - name: Install dependencies
        run: |
          cd /home/statsb/statsb-app
          npm install
          
      - name: Build application
        run: |
          cd /home/statsb/statsb-app
          npm run build